### ISSUE TITLE
Antena house CSS Renderer

### ISSUE THREAD

**Issue by withanage** [withanage/heimpt#18]
@kadowa 
Falls wir jetzt keine eindeutige Entscheidung zwischen AH und Prince schwierig sein sollte, wäre eine Untersuchng der AH-CSS Formatter gegen Prince  nötig, da diese auch css3 verwendet. 
http://www.antennahouse.com/antenna1/css/
@fkrb  was denkst Du ?

**Comment by fkrb** [comment]
@withanage
Ja, ein Vergleich wäre sinnvoll. Jemand müsste die CSS-Version des 
AH-Formatters herunterladen und installieren. Die Layoutbeispiele auf 
der Prince-Seite sind beeindruckend, ich fürchte aber, dass diese 
Beispiele nicht vollautomatisch erzeugt wurden.

Am 19.01.2016 um 13:08 schrieb Dulip Withanage:
>
> @kadowa <https://github.com/kadowa>
> Falls wir jetzt keine eindeutige Entscheidung zwischen AH und Prince 
> schwierig sein sollte, wäre eine Untersuchng der AH-CSS Formatter 
> gegen Prince nötig, da diese auch css3 verwendet.
> http://www.antennahouse.com/antenna1/css/
> @fkrb <https://github.com/fkrb> was denkst Du ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/withanage/mpt/issues/18>.
>

-- 
Frank Krabbes
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109
69117 Heidelberg

Tel: +49 (0)6221 542569
Fax: +49 (0)6221 542623

E-Mail: krabbes@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de

**Comment by kadowa** [comment]
Bei diesen Beispielen hier http://www.princexml.com/samples/ ist jeweils die HTML-Source dabei – damit müsste sich eigentlich nachvollziehen lassen, ob sich die entsprechende Ausgabe tatsächlich vollautomatisch erzeugen lässt.

**Comment by withanage** [comment]
@kadowa  in deinem link http://www.princexml.com/samples/
steht, dass prince direkt jats unterstützt. Kannst Du bitte das Beispiel da testen?
Das wäre ein großes Plus-punkt für prince.

**Comment by kadowa** [comment]
Das Beispiel lässt sich einwandfrei reproduzieren, s. https://github.com/withanage/mpt/blob/master/static/tests/misc/pdf/bmj_sample.prince.pdf.

**Comment by withanage** [comment]
@kadowa  , kannst Du dann Habenstein mit dem gleichen stylesheet produzieren und das Ergebnis hochladen ?

**Comment by kadowa** [comment]
Habe exemplarisch Kapitel 1 und 2 formatiert, Ergebnis s. https://github.com/withanage/mpt/blob/master/static/tests/habenstein/pdf/hst04.ch1.prince.pdf und https://github.com/withanage/mpt/blob/master/static/tests/habenstein/pdf/hst05.ch2.prince.pdf. Glaube allerdings nicht, dass uns das viel weiter bringt; das Stylesheet ist für Journal-Artikel konzipiert und das sieht man auch.

**Comment by withanage** [comment]
@kadowa danke.  ich finde die Ergebnisse nicht schlecht. Wenn Du bei ah css formatter weiter geht kannst du auch in html paar multilinguale texte einfügen. Ich verwende dieses lorem-ipsum zu geneirerren. http://generator.lorem-ipsum.info/

**Comment by fkrb** [comment]
Ich habe mir den Prince 10 angesehen (K.s Tests und und eigene) und bin (nach 2 Tagen) von Prince recht beeindruckt. Ich dokumentiere meine Ergebnisse der Übersicht halber erstmal in einem Excel-Sheet, aber negativ aufgefallen ist mir bisher nur:

- Man kann eine PDF-Datei nicht mit einer linken Seite beginnen lassen - das ist ungünstig, wenn ein Kapitel mit einem Starterbild auf der linken Seite beginnt (z.B. Sander oder die Ausstellungskataloge);
- man kann keine Seitenreihen mit gerader oder ungerader Seitenanzahl erzwingen;
- bei der Platzierung von Float-Objekten kann es sein, dass die Reihenfolge geändert wird (s. https://github.com/withanage/mpt/blob/master/static/tests/misc/pdf/floats-prince.pdf ). Das lässt sich beheben, indem man manuell die Referenz auf die Abbildung etwas nach hinten schiebt;
- es gibt kein Zeilenraster, das ist etwas lästig bei mehrspaltigen Layouts.

Ich habe noch keine Idee, wie sich die letzten beiden Punkte irgendwie lösen lassen. Wenn wir das nicht lösen können, wird die Paginierung des Buches schwierig. Hier müsste man gucken, ob der AH-CSS-Formatierer das unterstützt. Die FO-Variante kann das, hat aber wieder andere Nachteile.

**Comment by withanage** [comment]
@fkrb danke. Wäre doch auch gut, dass der excel Daten  in der Struktur @kadowa angelegt hat  https://github.com/withanage/mpt/wiki/doc2pdf:-Tests  
dokumentiert wird. @kadowa  wird   ah-css in der Test-suite intergrieren   und in eine 2.te schritt ein python post-processing skript vorbereiten. Wäre gut, dass du auch noch bei ah css  paar kritische tests machen könnte.

**Comment by fkrb** [comment]
Ja, das folgt alles noch :)

Zitat von Dulip Withanage <notifications@github.com>:

**Comment by kadowa** [comment]
Ich experimentiere gerade mit einem Habenstein-Kapitel, um den AHF-CSS-Formatter und Prince zu vergleichen; dabei bin ich auf diese Liste gestoßen: http://www.antennahouse.com/product/ahf60/docs/ahf-focss6.html Offenbar implementiert der CSS-Formatter nicht den kompletten Funktionsumfang des FO-Formatters. Insbesondere fehlen Optionen, um Fußnoten umfangreich zu formatieren, z.B. um Fußnoten in Spalten zu positionieren. Prince kann das hingegen. @fkrb, kannst du diese Einschätzung bestätigen? Damit dürfte der AHF-CSS-Formatter eigentlich raus sein.

**Comment by kadowa** [comment]
Zudem scheint mir der AHF-CSS nicht sonderlich robust zu sein; bei unbekannten im CSS-Properties stoppt er mit einer Fehlermeldung (Prince ignoriert diese, was natürlich auch nicht komplett unproblematisch ist). Mit der Angabe ```column-span: 2``` an der falschen (?) Stelle habe ich außerdem einmal diese Ausgabe bekommen:
![ahf_column_bug](https://cloud.githubusercontent.com/assets/8066366/12507266/eda15e20-c0f4-11e5-95c3-e8404eb5194b.png)

**Comment by kadowa** [comment]
Hier einmal der direkte Vergleich: https://github.com/withanage/mpt/blob/master/static/tests/habenstein/pdf/hst04.ch1.footnotes.ah.xmlcss.pdf und https://github.com/withanage/mpt/blob/master/static/tests/habenstein/pdf/hst04.ch1.footnotes.prince.pdf – beide wurden mit demselben Stylesheet erzeugt. Auffällig ist die unterschiedliche Platzierung der Fußnoten. Ich vermute, der Unterschied ist, dass Prince in Kauf nimmt, Fußnoten auf die nächste Seite zu verschieben, wenn sie nicht mehr auf die aktuelle passen:
```
prince: warning: cannot fit footnote(s) on page 10
prince: warning: cannot fit footnote(s) on page 25
```

**Comment by fkrb** [comment]
@kadowa Danke für diesen Vergleich. Dass Prince die Fußnote dann auf die 
nächste Seite verschiebt, ist nicht so schön, aber gut, dass der 
Formatierer in diesen Fällen eine Warnung ausgibt, sodass man hier 
immerhin manuell eingreifen kann.

Ja, dass der AHF-CSS-Formatierer nicht alle Funktionen der FO-Version 
übernimmt, ist interessant, zumal es sich bei der Fußnotenfunktion für 
die Platzierung innerhalb von Spalten um proprietäre Erweiterungen 
handelt. Ich habe jetzt selbst noch nicht ausprobiert, wie Prince 
Spalten-Fußnoten behandelt, aber einen proprietären Befehl gibt es für 
Prince. Was man auch mal testen könnte, sind zweispaltige Fußnoten unter 
einem einspaltigen Text, ich glaube aber nicht, dass das geht. Man 
müsste dann wohl ein zweispaltiges Grundlayout definieren und den 
eigentlichen Fließtext als span=2 definieren.

Größte Sorgen bereitet mir bei CSS for Paged Media im Moment, dass man 
die Seitenfolgen nicht kontrollieren kann. Ich kann z. B. nicht 
festlegen, dass die Seitenanzahl eines generierten Inhaltsverzeichnisses 
durch zwei teilbar sein muss und es notfalls mit leeren Seiten 
aufgefüllt werden muss. Hast Du evtl. eine Idee?

Am 22.01.2016 um 11:07 schrieb kadowa:
>
> Hier einmal der direkte Vergleich: 
> https://github.com/withanage/mpt/blob/master/static/tests/habenstein/pdf/hst04.ch1.footnotes.ah.xmlcss.pdf 
> und 
> https://github.com/withanage/mpt/blob/master/static/tests/habenstein/pdf/hst04.ch1.footnotes.prince.pdf 
> – beide wurden mit demselben Stylesheet erzeugt. Auffällig ist die 
> unterschiedliche Platzierung der Fußnoten. Ich vermute, der 
> Unterschied ist, dass Prince in Kauf nimmt, Fußnoten auf die nächste 
> Seite zu verschieben, wenn sie nicht mehr auf die aktuelle passen:
>
> |prince: warning: cannot fit footnote(s) on page 10 prince: warning: 
> cannot fit footnote(s) on page 25 |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/withanage/mpt/issues/18#issuecomment-173867738>.
>

-- 
Frank Krabbes
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109
69117 Heidelberg

Tel: +49 (0)6221 542569
Fax: +49 (0)6221 542623

E-Mail: krabbes@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de

**Comment by kadowa** [comment]
Das mit den Spalten habe ich oben nochmal ergänzt; AHF löst das anders als Prince, daher schien es erst so,als würde das nicht gehen.

Eine gerade Seitenzahl durch das automatische Auffüllen mit leeren Seiten zu erzeugen sollte gehen, schau mal hier: http://www.princexml.com/forum/topic/1344/even-page-count

**Comment by kadowa** [comment]
>  Dass Prince die Fußnote dann auf die nächste Seite verschiebt, ist nicht so schön, aber gut, dass der Formatierer in diesen Fällen eine Warnung ausgibt, sodass man hier immerhin manuell eingreifen kann.

Die Lösung von AHF ist anscheinend, stattdessen auf vielen Seiten einen Umbruch einzufügen. Dass dabei oft weniger als die Hälfte der Seite mit Text gefüllt ist, finde ich ziemlich unschön. Mich würde mal interessieren, welche Algorithmen hinter diesem beobachteten Verhalten stecken. Dann könnte man etwas fundierter vergleichen.

**Comment by fkrb** [comment]
Ich habe einmal eine überlange Fußnote mit AHF-FO gerechnet und ebenfalls einen interessanten Bug generiert, wie man auf Seite 1 sehen kann (https://github.com/withanage/mpt/blob/master/static/tests/misc/pdf/columns-ahf-fn-bug.pdf). Wäre das nicht, das Verhalten wäre eigentlich ok.

Mein Problem mit dem Textumfluss bei mehrspaltigen Abbildungen ist gelöst, das kann AHF-FO. Wie Prince wird aber die Reihenfolge der Abbildungen verändert, wenn die Abbildung schon vorher irgendwohin passt.
