### ISSUE TITLE
Abstände vor Überschriften

### ISSUE THREAD

**Issue by withanage** [withanage/heimpt#43]
<a href="https://github.com/ankosi"><img src="https://avatars.githubusercontent.com/u/11088169?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ankosi](https://github.com/ankosi)**
_Friday Aug 12, 2016 at 13:26 GMT_
_Originally opened as https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/66_

---

Vor Kapitelüberschriften (in Word Formatvorlage Überschrift 2) und Überschriften der Ebene 3 sollen die Abstände größer sein.

**Comment by withanage** [comment]
<a href="https://github.com/withanage"><img src="https://avatars.githubusercontent.com/u/1921992?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [withanage](https://github.com/withanage)**
_Monday Aug 22, 2016 at 12:40 GMT_

----

 @ankosi 
bei der Implemntierung ist mir aufgefallen, vielleicht ist es besser allgemein mehr Platz zwischen Überschriften. 
Habe allgemein auf 20 Pixeln gesetzt. Natürlich lässt es einschränken oder auch der Abstand vom unterhalb stehenden Text zusätzlich zu defineren.

**Comment by ankosi** [comment]
Bitte für Überschriftenebene 1 - vorgesehen für die "parts" eines Buches - auch diesen Abstand setzen. (Als ich das Issue eröffnet habe, habe ich das Gesamtdokument vergessen - dort braucht man ja auch Abstände zwischen den Großkapiteln/parts - sorry).

**Comment by withanage** [comment]
ok,   habe notiert ,  bei nächste Aktualisierung mache ich das.

**Comment by ankosi** [comment]
Werden die Abstände bei allen Büchern größer, sobald die Implementierung nicht mehr nur auf dem Test-, sondern auch auf dem Produktivserver aktiv ist?

**Comment by withanage** [comment]
ja, das habe ich allgemein gemacht. Sollte es  lieber nicht sein. Dann muss ich es  was anders einfallen lassen.

**Comment by ankosi** [comment]
Doch, soll schon allgemein gemacht werden.
