### ISSUE TITLE
(2) OMP import module

### ISSUE THREAD

**Issue by withanage** [withanage/heimpt#62]
- [x]  Make modules as a dependency  [Link](https://github.com/UB-Heidelberg/omp-modules)
- [x] OMP import plugin for MPT in  "static/tools/plugins/import/omp"
- [x] Import chapter submission files, check number of chapters and files
- [x] Add `full_file` to generated MPT json
- [x] Include metadata for chapter authors
- [x] Include metadata for: copyright-statement
- [ ] Include metadata for: series editors
- [ ] Include metadata for: license

Schritte:
* Datei hochladen in editor
* dann mpt als omp modul
* metadaten editieren in editor
* mpt richtig laufen und dateien schreiben

Info 
* Import only submission files from "Production ready files" (`file_stage == 11`)
* dateiname für metadaten ist file-id.bits.xml. dabei wird revision ignoriert

Generated MPT projects JSON:
* `path`: Like "static/files/presses/6/monographs/90/submission/"
* `name` should be "omp" + submission_id

OMP REST-API 
* z.B. /omp_rest/api/files/594?submissionId=48 soll die Datei Ausgegen

**Comment by withanage** [comment]
@isgrim 
https://withanage.github.io/mpt/_modules/mpt.html#MPT.run_modules
Beispiel ist  mpt.py --modules omp,ojs

**Comment by isgrim** [comment]
Danke!

**Comment by isgrim** [comment]
@withanage 
Wo sollen wir die Datenbanken URL für die Verbindung ablegen?
In den Portalen haben wir ja die Datei private/appconfig.ini.
Wie sollen wir das für das Import Plugin machen?
Sollen wir eine config.ini in "static.tools.plugins.import.omp" ablegen?
Oder in einem gemeinsamen Ordner?

**Comment by isgrim** [comment]
Neuer Änderungen: #73

**Comment by withanage** [comment]
@nils
Danke! Ich denke eine json config ist am besten. Lass mich das etwas durch den kopf gehen

**Comment by withanage** [comment]
@nils:
ich denke doch eine  settings.json besser, falls da etwas nicht zu stargk da gegen spricht. Pro Module eine configurations Datei. z.B. 
plugins/import/omp/settinngs.json

**Comment by isgrim** [comment]
@withanage Okay, dann machen wir eine settings.json.
Ich werde Donnerstag an der Stelle weitermachen.

**Comment by withanage** [comment]
@isgrim 
Habe eine ganz Simple Idee die Werte in Module zu tauschen.
man definiert eine Result Dictionary in dem  Module und füllt es mit Werten.
Nur als Idee, lass uns dann am Freitag ausführlich diskutieren.


https://github.com/withanage/mpt/blob/7c63ab05689321ccbdea5abf466735ecf2eac3ae/static/tools/mpt.py#L709
https://github.com/withanage/mpt/blob/7c63ab05689321ccbdea5abf466735ecf2eac3ae/static/tools/plugins/import/ojs/ojs.py#L17

**Comment by withanage** [comment]
Pfad für Eingabe Dateien in omp module
mpt/static/files/presses/<press_id>/monographs/<submission_id>/submission/proof/
Untersuchen: landen auch docx Datein direkt hier

**Comment by withanage** [comment]
![screenshot from 2017-05-10 16 44 11](https://cloud.githubusercontent.com/assets/1921992/25904620/0d0a3ea0-35a0-11e7-82bd-fe226531b1e6.png)
![screenshot from 2017-05-10 16 43 37](https://cloud.githubusercontent.com/assets/1921992/25904618/0d06e75a-35a0-11e7-9f1d-44c8af7b640f.png)
![screenshot from 2017-05-10 16 42 55](https://cloud.githubusercontent.com/assets/1921992/25904619/0d087084-35a0-11e7-9a5d-e2636f4dfb22.png)

**Comment by withanage** [comment]
doku : chapter zuordnung von einem Datei

**Comment by withanage** [comment]
dateiname für metadaten ist file-id.bits.xml. dabei wird revision ignoriert

**Comment by withanage** [comment]
Schritte:
Datei hochladen  in editor
dann mpt als omp modul
metadaten editieren in editor
mpt richtig laufen und  dateien schreiben

**Comment by isgrim** [comment]
Noch ein paar Fragen zu dem Metadaten Export aus OMP:
  * Von welchem Publication Format soll die DOI entnommen werden?
  * Woher die URN für eine Submission eingetragen? Momentan haben wir kein funktionierendes URN Plugin für OMP.
  * Alle Authoren und Herausgeber in Metadaten angeben oder nur diejenigen, für die "Include in Browse List" in OMP gesetzt ist? Das wäre dann so wie im Portal angezeigt wird.

**Comment by isgrim** [comment]
Weitere Fragen:
- [ ] Titel und Untertitel von Serien und Organisationen der Authoren mehrsprachig oder nur in Sprache der Submission?
- [ ] Woher die Lizenz URL und Permission Text nehmen?
- [ ] In OMP sind aktuell keine Serien Herausgeber eingetragen. Serien Herausgeber in Metadaten daher erstmal weglassen?
- [ ] Wie sollen die Metadaten Dateien für Kapitel heißen?

**Comment by withanage** [comment]
@isgrim 
api von omp /ojs wurde jetzt fest-gelegt  in diesem yaml file. wir können daran halten. 
https://gist.github.com/NateWr/310166836ebea9f6177be998607d1488

**Comment by isgrim** [comment]
Habe die besprochenen Änderungen/infos in der Beschreibung angepasst.
