### ISSUE TITLE
(4) Import plugin support in MPT

### ISSUE THREAD

**Issue by isgrim** [withanage/heimpt#71]
Import plugins would be stored in "static/tools/plugins/import/..."

- [x] add import mode in MPT with flag ,e.g., "--import=omp,ojs"
- [x] add interactive mode for MPT, run with flag "--interactive" from cli

**Comment by withanage** [comment]
@isgrim  FYI will enable interactive.
python mpt.py configurations/example.json   --interactive
in the current version , it will  proceed anyhow

**Comment by isgrim** [comment]
@withanage Thanks!

**Comment by withanage** [comment]
closing, thanks @isgrim
