### ISSUE TITLE
[html+css] Pdf-Archive  Format Unterstützung

### ISSUE THREAD

**Issue by withanage** [withanage/heimpt#8]

**Comment by kadowa** [comment]
mpdf scheint PDF/A zu unterstützen, s. http://mpdf1.com/manual/index.php?tid=420, für WeasyPrint (python) habe ich leider nichts vergleichbares gefunden.

**Comment by kadowa** [comment]
Wie (konkreter: mit welchem Tool) validieren wir PDF/A? Das scheint nicht-trivial zu sein (vgl. http://www.heise.de/newsticker/meldung/Kostenlose-Testsuite-fuer-PDF-A-Validierung-198192.html, http://www.pdfa.org/2011/09/validierung-von-pdfa/?lang=de).

@fkrb, irgendwechle Erfahrungen auf dem Gebiet?

**Comment by lmaylein** [comment]
Bislang validieren wir gar nicht. Bei den selbsterzeugten PDF/A-Dateien verlassen wir uns auf die Tools, mit welchen die Dateien erzeugt werden.

**Comment by withanage** [comment]
[Online!](http://www.pdf-tools.com/pdf/pdfa-online-pruefen.aspx) Version vom [3 Hights !] (http://www.pdf-tools.com/pdf/pdf-validator-pdfa-validieren-iso.aspx)
scheint  ziemlich gut zu funktionieren.
Habe unserem indesign habenstein getestet und  sogar eine Menge Fehler gefunden.

**Comment by lmaylein** [comment]
Gut und schlecht. D.h. Indesign erzeugt ein angebliches PDF/A, das aber gar keines ist?

**Comment by fkrb** [comment]
Kannst Du mir das Protokoll/Log bitte einmal zusenden?

Herzlich,
F.

Am 13.11.2015 um 09:50 schrieb Dulip Withanage:
>
> Online! <http://www.pdf-tools.com/pdf/pdfa-online-pruefen.aspx> 
> Version vom 3 Hights ! 
> <http://www.pdf-tools.com/pdf/pdf-validator-pdfa-validieren-iso.aspx>
> scheint ziemlich gut zu funktionieren.
> Habe unserem indesign habenstein getestet und sogar eine Menge Fehler 
> gefunden.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/withanage/mpt/issues/8#issuecomment-156364587>.
>

-- 
Frank Krabbes
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109
69117 Heidelberg

Tel: +49 (0)6221 542569
Fax: +49 (0)6221 542623

E-Mail: krabbes@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de

**Comment by withanage** [comment]
doch, es ist pdf-a, aber nicht 100% valide , wie es aussieht.
@AnjaKonopka  bestätigt mir das KNV 
"PDF/X-1a_2003 ausdrücklich empfehlen, es aber nicht kontrollieren, sondern das in unserer Verantwortung liegt. "
Daher KNV nimmt es von uns. D.h. in 2.Band sollten wir noch indesign pdf konkreter kontrollieren?

**Comment by withanage** [comment]
@fkrb  geemailt-

**Comment by kadowa** [comment]
@lmaylein, offenbar nicht nur InDesign. Ich habe letzte Woche ebenfalls mit 3-Heights getestet: Ein automatisch mit HTML2PDF (via mpdf mit PDF/A-Funktion) erzeugte [Variante des Habenstein-Bands](https://github.com/withanage/mpt/tree/master/static/tests/habenstein/pdf/html2pdfA) war nicht valide. Daraufhin habe ich mit einigen mit Latex erzeugten PDF/A-Dokumenten aus heiDOK (u.a. meiner eigenen Diss) getestet – auch alle nicht 100% valide.

**Comment by lmaylein** [comment]
Mit welcher PDF/A-Version hast Du getestet?
Und dann stellt sich natürlich noch die Frage, ob die evtl. auch überpenibel testen, weil sie was verkaufen wollen :-)

**Comment by kadowa** [comment]
Ich habe verschiedene getestet und bei allen Fehlermeldungen bekommen. Die Frage, was da eigentlich geprüft wird kam mir aber auch schon; daher die Frage und der obige Verweis auf den Heise-Artikel. Wenn es eigene Testsuites für PDF/A-Validierungssoftware gibt, liegt der Verdacht nahe, dass es sehr unterschiedliche Auffassungen von Validierung gibt.

**Comment by fkrb** [comment]
Die PDF/A-Version ist ein wichtiger Punkt. PDF/A-1a und -2a sind in 
ihren Anforderungen recht rigide, während PDF/A-1b, -2b, -2u weniger 
anspruchsvoll sind. Ich kann mir gut vorstellen, dass PDF-Renderer die 
rigiden Standards möglicherweise gar nicht zu 100% unterstützen (mPDF 
unterstützt nur 1b, wie ich sehe). Der Acrobat Pro kann nach den 
verschiedenen PDF/A-Standards validieren, besitzt aber (noch) keine 
Prüfroutine für PDF/A-3 - das ist aber auch noch kein ISO-Standard, wenn 
ich hier up-to-date bin. PDF-Dokumente lassen sich in Adobe Acrobat Pro 
auch nach PDF/A konvertieren. Das habe ich bisher nicht getestet und bin 
auch eher skeptisch, ob man dabei wirklich -1a oder -2a-konforme 
Dokumente herausbekommt, oder ob der sich in manchen Fällen die 
Konformität herbeitrickst. Indesign beherrscht nur PDF/X, das wir für 
den Austausch mit der Druckerei brauchen. Die Druckereien sollten zwar 
auch mit PDF/A umgehen können, man kann dann aber ggf. nicht alle 
Möglichkeiten des Drucks nutzen.

Validiert wurde nach 1a. Aus dem Logfile geht u.a. hervor, dass er bei 
Unicode-Zeichen, der Schriftarteneinbettung, den Farbräumen und 
ICC-Farbprofilen meckert. Bei den Metadaten (XMP) stimmt auch etwas nicht.

~F.

Am 16.11.2015 um 08:23 schrieb lmaylein:
>
> Mit welcher PDF/A-Version hast Du getestet?
> Und dann stellt sich natürlich noch die Frage, ob die evtl. auch 
> überpenibel testen, weil sie was verkaufen wollen :-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/withanage/mpt/issues/8#issuecomment-156945359>.
>

-- 
Frank Krabbes
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109
69117 Heidelberg

Tel: +49 (0)6221 542569
Fax: +49 (0)6221 542623

E-Mail: krabbes@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de

**Comment by withanage** [comment]
@kadowa  habe ich übernommen.

**Comment by withanage** [comment]
jetzt wird nur gitlab zur Kommunikation verwednet.
